#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 10(bad luck-> 4, good luck-> 8, Best School-> other)

b=1

while [[ $b -le 10 ]]
do
	if [[ $b -eq 4 ]];
then
		echo "bad luck";
	elif [[ $b -eq 8 ]]; then
		echo "good luck";
	else
		echo "Best School";
	fi
	b=$(( b+1 ));
done
