#!/usr/bin/env bash
# Write numbers from 1 to 20, after 4 add "bad luck from China", after 9 add "bad luck from Japan", after 17 add "bad luck from Italy"

b=1
while [ $b -le 20 ]
do
  echo "$b";
  case $b in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( b++ ));
done
