#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes

time=0

while [ $time -le 12 ]
do
  echo "Hour: $time";
  min=1
  while [ $min -le 59 ]
  do
    echo "$min";
    (( min++ ));
  done
  (( time++ ));
done
