#!/usr/bin/env bash
# Get process IDs -> (PIDs) of Gunicorn processes

gunicorn_pids=$(pgrep gunicorn)

# Output current Gunicorn processes
echo "Current Gunicorn processes:"
ps aux | grep 'gunicorn' | grep -v 'grep'

# Existing Gunicorn process for graceful reload
for pid in $gunicorn_pids; do
    if ps -p $pid > /dev/null; then
        echo "Gracefully reloading Gunicorn process with PID $pid"
        kill -HUP $pid
    else
        echo "Process with PID $pid not found."
    fi
done

# OUTPUT UPDATED Gunicorn processes
echo "Updated Gunicorn processes:"
ps aux | grep 'gunicorn' | grep -v 'grep'
